### ISSUE TITLE
dynamic install_requires breaks universal wheels

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.schema#19]
As in https://github.com/zopefoundation/ZODB/issues/36, the conditional inclusion of `ordereddict` in `install_requires` breaks things.

**Comment by jamadden** [comment]
This was fixed with the removal of Python 2.6 support in https://github.com/zopefoundation/zope.schema/commit/cd3d77c98455a1f872e18c28730dc5c77719dff4.
