### ISSUE TITLE
"AbstractCollection" should allow to define "value_type" in a derived class

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/zope.schema#23]
Currently, "AbstractCollection" looks like:

```
class AbstractCollection(MinMaxLen, Iterable)
    value_type = None
    unique = False

    def __init__(self, value_type=None, unique=False, **kw):
        super(AbstractCollection, self).__init__(**kw)
        # whine if value_type is not a field
        if value_type is not None and not IField.providedBy(value_type):
            raise ValueError("'value_type' must be field instance.")
        self.value_type = value_type
        self.unique = unique
```

This makes it difficult to define "value_type" in a derived class. I suggest to use a "marker" as default value for the "value_type" parameter of `AbstractCollection.__init__` and use the class default in this case.

**Comment by icemac** [comment]
Interesting idea. A pull request is sincerely welcome.

**Comment by d-maurer** [comment]
Other fields could get similar enhancements: e.g. the "Object" field for the "schema" parameter.

It may take some time before I find time to look more closely into this.
