### ISSUE TITLE
setting _type on choice-field by given vocabulary

### ISSUE THREAD

**Issue by iham** [zopefoundation/zope.schema#29]
to make use of _type in plone.supermodel on the Choice field i would like to set _type according to its given vocabulary by using:

```python
_type = type(vocabulary.by_value.keys()[0])
```

but i cant find any place where to do that:

in Choice.__init__() during start of the zope instance, i do get the vocabularyName, but cant find a vocabulary by using
```python
vcf = getUtility(IVocabularyFactory, field.vocabularyName)
```
as there is no vocabulary existing at that moment.

i also tried Choice._validate() and Choice.set().
i never reach set(), which was surprising and _validate() feels like the wrong place ...

so what can i do?

**Comment by agroszer** [comment]
I think you're mixing up configuration and execution time properties.

```_type``` is set when the Field is instantiated (configuration time)

At that time you should not try to get a vocabulary, because your app might be in the middle of the very first imports and vocabularies probably depend on application data.
Vocabularies are usually instantiated when the app is up and running.

**Comment by iham** [comment]
that is possibly true ;)

the typecast of plone.supermodel is using _type. to get the type right for choices, this would be needed to be defined, when the field gets the vocabulary. but i don't see, if this is possible and if: where ...

**Comment by agroszer** [comment]
Well, accessing private attributes is generally a bad idea. Also the vocabulary could have zero items. More and more arguments against this.

**Comment by iham** [comment]
any advice for a solution instead of arguments against it?

if not, my solution is https://github.com/plone/plone.supermodel/pull/17 which i also think is not good (as i deal with private vars)

**Comment by agroszer** [comment]
Oh well, as you see a lot can happen, there are no guarantees. You won't be able to reliably determine the type at config time. Not even when the form is instantiated. Sorry, I don't have a better idea.

**Comment by iham** [comment]
ok, thanks :)

**Comment by davisagli** [comment]
It's also possible (though probably usually a bad idea) to have a vocabulary where different terms have different types.

David Glick
(mobile)

**Comment by iham** [comment]
i know this is possible, but where is it used? never seen one.
