### ISSUE TITLE
MessageID as description...

### ISSUE THREAD

**Issue by goschtl** [zopefoundation/zope.schema#63]
Hi,

i have a problem with this change in zope.schema...

            if description:
                # Fix leading whitespace that occurs when using multi-line
                # strings.
                description = '\n'.join(_DocStringHelpers.docstring_to_lines(description)[:-1])
                __doc__ = "%s\n\n%s" % (title, description)

Assuming i have defined a Field where i add a _(translation) as description.

test = schema.Choice(title=_(u'TITLE'), description=u('DESCRIPTION'))

What happens in the code is now that the description which from the class
<type 'zope.i18nmessageid.message.Message'>
gets typecasted to an unicode.

I guess this is a bug.

Christian

**Comment by jamadden** [comment]
Interesting. I see how we can avoid that. I'll create a PR.

**Comment by goschtl** [comment]
i guess it is easy to fix
this should do it:

__doc__ = "%s\n\n%s" % (title, '\n'.join(_DocStringHelpers.docstring_to_lines(description)[:-1]))
