### ISSUE TITLE
Borked interface resolution order for boolean field

### ISSUE THREAD

**Issue by ale-rt** [zopefoundation/zope.schema#80]
If I take a boolean field I would expect IBool to be the first interface,compare the output of the field `__iro__` with other fields.
```
In [23]: ITestContent['_bool'].__provides__.__iro__
Out[23]: 
(<InterfaceClass zope.schema._bootstrapinterfaces.IFromUnicode>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IFromBytes>,
 <InterfaceClass zope.schema.interfaces.IBool>,
 <InterfaceClass zope.schema.interfaces.IField>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IValidatable>,
 <InterfaceClass zope.interface.interfaces.IAttribute>,
 <InterfaceClass zope.interface.interfaces.IElement>,
 <InterfaceClass zope.interface.Interface>)

In [24]: ITestContent['_decimal'].__provides__.__iro__
Out[24]: 
(<InterfaceClass zope.schema.interfaces.IDecimal>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IFromUnicode>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IFromBytes>,
 <InterfaceClass zope.schema.interfaces.INumber>,
 <InterfaceClass zope.schema.interfaces.IMinMax>,
 <InterfaceClass zope.schema.interfaces.IOrderable>,
 <InterfaceClass zope.schema.interfaces.IField>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IValidatable>,
 <InterfaceClass zope.interface.interfaces.IAttribute>,
 <InterfaceClass zope.interface.interfaces.IElement>,
 <InterfaceClass zope.interface.Interface>)

In [25]: ITestContent['_float'].__provides__.__iro__
Out[25]: 
(<InterfaceClass zope.schema.interfaces.IFloat>,
 <InterfaceClass zope.schema.interfaces.IReal>,
 <InterfaceClass zope.schema.interfaces.IComplex>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IFromUnicode>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IFromBytes>,
 <InterfaceClass zope.schema.interfaces.INumber>,
 <InterfaceClass zope.schema.interfaces.IMinMax>,
 <InterfaceClass zope.schema.interfaces.IOrderable>,
 <InterfaceClass zope.schema.interfaces.IField>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IValidatable>,
 <InterfaceClass zope.interface.interfaces.IAttribute>,
 <InterfaceClass zope.interface.interfaces.IElement>,
 <InterfaceClass zope.interface.Interface>)
```
This prevents to register specific adaters for the IBool interface, see https://github.com/plone/plone.rfc822/pull/6/files#diff-13c585cfb8d0755a94087390ae8b22e4R30

**Comment by ale-rt** [comment]
@jamadden I think you probably have a good idea on how to fix this given your recent work on the `IFrom*` interface implementation.

**Comment by jamadden** [comment]
This is the case for *many* of the fields, including `Text`, `TextLine` and `Int`, due to the way they are implemented in `_bootstrapfield.py` and then later "assigned" their final interfaces in `_field.py`:
```python
classImplements(Text, IText)
classImplements(TextLine, ITextLine)
classImplements(Password, IPassword)
classImplements(Bool, IBool)
classImplements(Iterable, IIterable)
classImplements(Container, IContainer)

classImplements(Number, INumber)
classImplements(Complex, IComplex)
classImplements(Real, IReal)
classImplements(Rational, IRational)
classImplements(Integral, IIntegral)
classImplements(Int, IInt)

classImplements(Object, IObject)
```

e.g., for Text:
```pycon
>>> from zope.schema import Text
>>> list(providedBy(Text()).flattened())
[<InterfaceClass zope.schema._bootstrapinterfaces.IFromUnicode>,
 <InterfaceClass zope.schema.interfaces.IText>,
 <InterfaceClass zope.schema.interfaces.IMinMaxLen>,
 <InterfaceClass zope.schema.interfaces.ILen>,
 <InterfaceClass zope.schema.interfaces.IIterable>,
 <InterfaceClass zope.schema.interfaces.IField>,
 <InterfaceClass zope.schema._bootstrapinterfaces.IValidatable>,
 <InterfaceClass zope.interface.interfaces.IAttribute>,
 <InterfaceClass zope.interface.interfaces.IElement>,
 <InterfaceClass zope.interface.Interface>]
```

It has been done this way since at least 3.4.0. I'm not sure what else can be done.

**Comment by davisagli** [comment]
Seems like a big problem to me -- it means that an adapter registered for `IFromUnicode` takes precedence over one registered for a specific field type.

**Comment by mgedmin** [comment]
Would it help if IText et al explicitly inherited IFromUnicode and similar "mixin" interfaces?

**Comment by jamadden** [comment]
> Would it help if IText et al explicitly inherited IFromUnicode and similar "mixin" interfaces?

It seems to me those are properties of the implementation of the field, not the contract of its interface. OK, I think `IText` might be a bit of a special case, `IFromUnicode` seems reasonable to expect of a `IText` field. But not necessarily for an `IBool` field---indeed, zope.configuration implements its Bool's `fromUnicode` method *very* differently than the `Bool` class here does, and maybe there's an IBool implementation that doesn't want to accept strings at all.

The other option I can think of is to remove all the `@implementer` decorators in the `_bootstrapfields.py` file, and then manually move all of those declarations to the `classImplements` block in `_field.py`. But that's tedious. Also, does `classImplements` actually make any guarantees about IRO on the final object?

**Comment by jamadden** [comment]
> But that's tedious. Also, does classImplements actually make any guarantees about IRO on the final object?

No, not really. It just sticks whatever you give it on the *end* of the list of things already directly implemented. That can lead to really messed up IROs in the case of inheritance (I had to tweak it for that reason in https://github.com/zopefoundation/zope.interface/pull/182, but that doesn't solve the issue here) . Arguably it should put what you're giving it at the *front* of the list, or at the very least you should get to choose (probably a separate function). 

I mean, you can go back in and manually fix it by re-arranging `implementedBy(Bool).__bases__`, but that's cheating. Still, it is an option. If https://github.com/zopefoundation/zope.interface/pull/182 gets merged, I'll need to do a bit of cleanups on about 5 of the IROs here anyway (all having to do with strings, IIRC).
