### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by PythonLinks** [zopefoundation/zope.schema#84]
It would be wonderful if I could add a placeholder to a zope.schema field. 
Or any other htmattribute for that matter.

**Comment by d-maurer** [comment]
> It would be wonderful if I could add a placeholder to a zope.schema field.
> Or any other htmattribute for that matter.

Can you provide an example what you mean by *placeholder*?

You could look at the `tag` module of [dm.zope.schema](https://pypi.org/project/dm.zope.schema/) and the related example in the example section. It uses the "tagged values" concept of `zope.interface` to add additional information to `zope.schema` fields. I use it in `dm.zope.reseller` to enhance schemas with information relevant for the management of corresponding data records in a relational database.

**Comment by jamadden** [comment]
It's also *possible* (though probably not recommended --- I would stick with tags) to add new attributes to stock fields; these values are copied into bound instances:
```pycon
>>> from zope.schema import *
>>> from zope.interafce import Interface
>>> from zope.interface import Interface
>>> class IFoo(Interface):
...     field = Bytes(title='a bytes')
...     field.placeholder = 'my placeholder'
...
>>> IFoo['field'].placeholder
'my placeholder'
>>> IFoo['field'].bind(object()) is IFoo['field']
False
>>> IFoo['field'].bind(object()).placeholder
'my placeholder'
```

**Comment by jamadden** [comment]
Closing since there've been no updates.
