### ISSUE TITLE
#87 breaks persistent Text fields

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.schema#90]
We persist some schemas that use fields. Setting `unicode_normalization` in `Text.__init__` breaks persistent loading of such schemas.

**Comment by jamadden** [comment]
IIUC, [a class attribute](https://github.com/zopefoundation/zope.schema/pull/87#discussion_r379381515) would solve that?

```python
class Text(MinMaxLen, Field):
    unicode_normalization = 'NFC'

    def __init__(self, *args, **kwargs):
        self.unicode_normalization = kwargs.pop(
            'unicode_normaliaztion',
            type(self).unicode_normalization)
        super(Text, self).__init__(*args, **kwargs)
```
